spring.application.name=RewardProject
preference.summary.stand1.name=North Stand
preference.summary.stand1.available_seats=150
preference.summary.stand1.discount_price=10.0
preference.summary.stand1.preferred_seats=25

preference.summary.stand2.name=South Stand
preference.summary.stand2.available_seats=150
preference.summary.stand2.discount_price=15.0
preference.summary.stand2.preferred_seats=30

preference.summary.stand3.name=East Stand
preference.summary.stand3.available_seats=150
preference.summary.stand3.discount_price=12.0
preference.summary.stand3.preferred_seats=40

preference.summary.stand4.name=West Stand
preference.summary.stand4.available_seats=150
preference.summary.stand4.discount_price=17.0
preference.summary.stand4.preferred_seats=15

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/RewardProjectDB
spring.datasource.username=postgres
# !!! CHANGE THIS TO YOUR POSTGRES PASSWORD !!!
spring.datasource.password=password

# JPA Settings
# This tells Hibernate (the JPA provider) how to talk to Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# This automatically creates/updates your database tables based on your Entity classes
spring.jpa.hibernate.ddl-auto=create